### Vectors and Matrices:

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
array1 = np.arange(10).reshape(5,2)
array1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
print(type(array1))
array1.dtype

<class 'numpy.ndarray'>


dtype('int64')

In [ ]:
array2 = array1.astype(float)
array2

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [ ]:
# create an array with integers
array2 = np.array([1, 2, 3, 4, 5])
print("Original array type:", array2.dtype)

# convert to float
array2_float = array2.astype(float)
print("Converted array type:", array2_float.dtype)
print("Converted array:", array2_float)

# convert to string
array2_str = array2.astype(str)
print("Converted array type:", array2_str.dtype)
print("Converted array:", array2_str)

Original array type: int64
Converted array type: float64
Converted array: [1. 2. 3. 4. 5.]
Converted array type: <U21
Converted array: ['1' '2' '3' '4' '5']


In [ ]:
array1.ndim

2

In [ ]:
array1+array2

array([[ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.]])

In [ ]:
vector_1 = np.arange(3)
vector_1

array([0, 1, 2])

In [ ]:
vector_2 = np.arange(4,7)
vector_2

array([4, 5, 6])

In [ ]:
vector_1 + vector_2

array([4, 6, 8])

In [ ]:
vector_1 - vector_2

array([-4, -4, -4])

elementwise multiplication

In [ ]:
vector_1 * vector_2

array([ 0,  5, 12])

cross product

dot product

In [ ]:
dot_product = np.dot(vector_1, vector_2)
print(dot_product)
dot_product

17


np.int64(17)

In [ ]:
cross_product = np.cross(vector_1, vector_2)
cross_product

array([-4,  8, -4])